github: [metadata]

remote_theme: eclipsefdn/jekyll-theme-eclipsefdn
#theme: jekyll-theme-eclipsefdn # for local use

title: [Eclipse Implementation of Jakarta XML Binding]
description: [Implementation of Jakarta XML Binding]

links:
  source: https://github.com/eclipse-ee4j/jaxb-ri
  javadocs: javadocs/index.html
  download: https://github.com/eclipse-ee4j/jaxb-ri/releases/tag/2.3.2-RI
  mailinglist: https://accounts.eclipse.org/mailing-list/jaxb-dev
