github: [metadata]

remote_theme: eclipsefdn/jekyll-theme-eclipsefdn
#theme: jekyll-theme-eclipsefdn # for local use

title: [Jakarta XML Binding]
description: [Implementation of Jakarta XML Binding]

links:
  source: https://github.com/eclipse-ee4j/jaxb-ri
  api: https://javadoc.io/doc/jakarta.xml.bind/jakarta.xml.bind-api/4.0.2/
  spec: https://jakarta.ee/specifications/xml-binding/
  guide: https://eclipse-ee4j.github.io/jaxb-ri/4.0.5/docs/
  javadocsrt: https://javadoc.io/doc/com.sun.xml.bind/jaxb-impl/4.0.5/
  javadocsxjc:  https://javadoc.io/doc/com.sun.xml.bind/jaxb-xjc/4.0.5/
  javadocsjxc:  https://javadoc.io/doc/com.sun.xml.bind/jaxb-jxc/4.0.5/
  download: https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-ri/4.0.5/jaxb-ri-4.0.5.zip
  mailinglist: https://accounts.eclipse.org/mailing-list/jaxb-impl-dev