/*
 * Copyright (c) 1997, 2020 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License v. 1.0, which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/**
 * XML Schema writer generated by TXW.
 */
@com.sun.xml.txw2.annotation.XmlNamespace("http://www.w3.org/2001/XMLSchema")
package org.glassfish.jaxb.runtime.v2.schemagen.xmlschema;
